services:
  roam-server:
    image: docker.io/nginx:1.27
    container_name: roam-server
    volumes:
      - ./public:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    ports:
      - "8005:80"
    restart: always
    labels:
      description: "メモ"

  three-server:
    image: docker.io/node:22
    container_name: three-server
    volumes:
      - ./three:/app/three
      - ./public:/app/public
    working_dir: /app/three
    ports:
      - "3333:3333"
    restart: always
    command: sh -c "npm install && npm start"
    environment:
      - PORT=3333
      - PUBLIC_DIR=/app/public
    labels:
      description: "3D Viewer Server"
